
variable "vcenter_server" {
}

variable "username" {
}

variable "password" {
}

variable "datastore" {
}

variable "folder" {
} 

variable "vm_name" {
} 

variable "host" {
}

variable "cluster" {
} 

variable "network" {
} 


source "vsphere-iso" "autogenerated_1" {
  CPUs                 = 4
  RAM                  = 4096
  boot_command         = ["<esc><esc><esc><esc>e<wait>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "<del><del><del><del><del><del><del><del>", "linux /casper/vmlinuz --- autoinstall ds=\"nocloud-net;seedfrom=http://{{ .HTTPIP }}:{{ .HTTPPort }}/\"<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>", "<enter><f10><wait>", "<wait300>"]
  boot_wait            = "3s"
  cluster              = "${var.cluster}"
  convert_to_template  = false
  datastore            = var.datastore
  disk_controller_type = [ "pvscsi" ]
  folder               = "Templates"
  guest_os_type        = "ubuntu64Guest"
  http_directory       = "./http"
  insecure_connection  = "true"
  iso_checksum         = "sha256:e4089c47104375b59951bad6c7b3ee5d9f6d80bfac4597e43a716bb8f5c1f3b0"
  iso_urls             = ["iso/ubuntu-21.04-live-server-amd64.iso", "https://releases.ubuntu.com/21.04/ubuntu-21.04-live-server-amd64.iso"]
  network_adapters {
    network      = var.network
    network_card = "vmxnet3"
  }
  password               = var.password
  shutdown_command       = "sudo shutdown -P now"
  ssh_handshake_attempts = "100"
  ssh_password           = "ubuntu"
  ssh_port               = 22
  ssh_timeout            = "20m"
  ssh_username           = "ubuntu"
  storage {
    disk_size             = 40960
    disk_thin_provisioned = false
  }
  username       = var.username
  vcenter_server = var.vcenter_server
  vm_name        = var.vm_name
}

build {
  sources = ["source.vsphere-iso.autogenerated_1"]

}
